theme: jekyll-theme-midnight
title: Akber Iqbal on Github pages
description: Full stack web developer, React, Node, AWS serverless responsive, progressive web apps with microservices, REST, graphQL, noSQL, CSS3
